name: FastAPI Docker ML Run

on:
  push:
    branches:
      - main

jobs:
  build-and-test-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t ml-fastapi-app .

      - name: Run FastAPI Container in Background
        run: |
          docker run -d -p 8000:8000 --name api-service ml-fastapi-app
          sleep 5

      - name: Test API Endpoint Health Check
        run: |
          curl --fail http://localhost:8000/ || exit 1